name: Generate RSS Feed

on:
  schedule:
    - cron: '10 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python deps
        run: python -m pip install --upgrade requests beautifulsoup4 lxml

      - name: Build RSS via Python
        run: |
          # ↑ 上記のPythonコードをここにコピペ

      - name: Show files for debug
        run: ls -lhA

      - name: Move & stage rss.xml
        run: |
          mv -f new_rss.xml rss.xml
          ls -lhA
          git add rss.xml

      - name: Commit & push if changed
        run: |
          if git diff --cached --quiet; then
            echo "Nothing to commit"; exit 0; fi
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Update URA RSS feed"
          git push
